### ISSUE TITLE
Can only get the site to run locally

### ISSUE THREAD

**Issue by cmarabate** [adamelevate/aomSpellbook#1]
Hello, I'm very impressed by this site and I would like to create a very similar site for Age of Magic that allows you to select each of the heroes in your opponents squad and have it return a list of squad combinations that can beat that opponent.

So I feel like this site would be a perfect starting point for me since you already have most the AoM data in there already.

But I spent most the day yesterday trying to figure out how to push it live. Ideally I would like to be able to host it on Netlify. Is that possible or does this site require me to use Firebase's hosting? I tried setting it up in my Firebase account yesterday and didn't have any luck. This is the best I was able to do....
[https://aomspellbook.cmarabate.com/](https://aomspellbook.cmarabate.com/)

It says I successfully setup firebase hosting but it doesn't show me anything except a link to the Open Hosting Docs.

I'm not sure if you are interested in AoM still or that you have any free time but if so, please let me know. It would make things go much smoother with you on the team =).

But either way, could you please help me figure out how to get a copy of your site live?

Thanks,

Chris

**Comment by adamelevate** [comment]
Hey Chris, thanks for your kind words and interest.

This app is built with Vue.js, so once you build it locally, you'll have a dist folder that you can literally drop into any hosting. If you installed vue's cli, then you can just run `vue ui` in the command, in the browser use the ui to navigate to your project, run local or build from there, or if you use 'npm run build' in the command line. That should let you export the public files to host anywhere you want.

It's pretty old at this point, so you'll want to update the dependencies, otherwise it may not run very well. [https://flaviocopes.com/update-npm-dependencies/](https://flaviocopes.com/update-npm-dependencies/)

I started this project to learn Firebase's firestore db, which I love btw, but in the end I just used local json. Alas, I haven't updated it in a while, knowing the game has moved on quite a bit too Lemme know if you have any more questions.

**Comment by cmarabate** [comment]
Thanks, that was a big help!

Apparently my issue was that "/dist" was in to the .gitignore file and since I deploy my sites from my GitHub repos to Netlify, there was no dist folder at all for Netlify to deploy the site with.

I now have a copy of your site hosted on Netlify...
[https://aomspellbook.cmarabate.com](https://aomspellbook.cmarabate.com)

So Firebase is not needed at all right? I see a lot of references to firebase/firestore in the code which seems odd if Firebase is not needed...
![image](https://user-images.githubusercontent.com/12236062/78706073-776d2000-78dc-11ea-9d4c-52d9888af25c.png)

Is it all left over from when you were trying to make it use Firebase's firestore db?

**Comment by adamelevate** [comment]
Yeah, lol, whoops. I might have some code debt still in there.

Site looks good man!

The dist folder needs to be excluded from the repo since it can be kinda big, but also, everytime you make a change to the build, it auto-versions the files for cache busting, so it would be pointless to save those to the repo. Just run the build process and it will compile that folder for you.

You can remove all references to firebase, it doesn't use it in any way. I had started the process to use firebase, which I do on many other projects, but I spent so much time reorganizing the spells and such that it became too much work as firebase doesn't have great "import" functions, you  have to make pretty much all your tools yourself. I could have used it when I was done, but by then I was ready to ship and be done, lol.

**Comment by cmarabate** [comment]
Cool, that is what I figured.

Hmmm, about the dist folder.... Since I setup Netlify to automatically rebuild the site every time I push a commit to my repo, don't I need to include the dist folder in my repo?

Thanks, will do! And thanks for the explanation about why you added it, that is good to know.
